### ISSUE TITLE
No Calls, Voice or Video

### ISSUE THREAD

**Issue by clintonruairi** [sayedulsayem/whatsapp-linux-desktop#2]
"Full Functionality: Access all the features you love from WhatsApp Web, including text messaging, voice, video calls, and file sharing" - app does not have voice or video calls

**Comment by sayedulsayem** [comment]
@clintonruairi 
This was simply an honest mistake. The application does not support any calling features. Thank you for bringing this to my attention; I will remove that information from the descriptions.

For clarification, WhatsApp's web version does not have calling capabilities. This application is just a wrapper for the web version, and as third-party developers, we cannot include those features.

**Comment by clintonruairi** [comment]
the README still says your wrapper supports voice and video calls. This is misleading, and leads to incorrect information in search results

**Comment by sayedulsayem** [comment]
@clintonruairi
I apologize for the delay. I have updated the README. Thank you.

**Comment by shafayetejaman** [comment]
@sayedulsayem 

There should be a limitation section on the readme page, I though it should make call by reading this 

<img width="1472" height="244" alt="Image" src="https://github.com/user-attachments/assets/b0e51cdc-67d9-4c32-9b11-578c538c5d82" />
